version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: git-ctx
    binary: git-ctx
    dir: ./cmd/git-ctx
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/lvluu/git-ctx/internal/app.version={{.Version}} -X github.com/lvluu/git-ctx/internal/app.commit={{.Commit}} -X github.com/lvluu/git-ctx/internal/app.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
  - id: gc
    binary: gc
    dir: ./cmd/git-ctx
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/lvluu/git-ctx/internal/app.version={{.Version}} -X github.com/lvluu/git-ctx/internal/app.commit={{.Commit}} -X github.com/lvluu/git-ctx/internal/app.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
