package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// AppConfig is the unified configuration for git-ctx stored at ~/.git-ctx.yaml.
type AppConfig struct {
	// ProfilesPath is where git-ctx profiles are stored (JSON file).
	ProfilesPath string `yaml:"profiles_path"`

	// DirectoryRules maps directory path prefixes to profile names.
	// Longest matching prefix wins.
	DirectoryRules []DirectoryRule `yaml:"directory_rules"`

	Worktree AppWorktreeConfig `yaml:"worktree"`

	// path is the file this config was loaded from (not serialized).
	path string
}

// DirectoryRule maps a directory path prefix to a profile name.
type DirectoryRule struct {
	Pattern string `yaml:"pattern"`
	Profile string `yaml:"profile"`
}

// AppWorktreeHooks holds hook commands that run at various lifecycle points.
type AppWorktreeHooks struct {
	// PostCreate runs after a worktree is created (before files are synced).
	PostCreate []string `yaml:"post_create"`
}

// AppWorktreeConfig holds worktree-related settings.
type AppWorktreeConfig struct {
	// DefaultMode is "symlink" (default) or "copy".
	DefaultMode string `yaml:"default_mode"`
	// Hooks are commands to run at various lifecycle points.
	Hooks AppWorktreeHooks `yaml:"hooks"`
}

// MatchDirectoryRule finds the best-matching profile for dir using longest-prefix matching.
// ~ in patterns is expanded to the user home dir. Returns ("", false) if no rule matches.
func (cfg AppConfig) MatchDirectoryRule(dir string) (profile string, ok bool) {
	homeDir, _ := os.UserHomeDir()
	best := ""
	bestLen := -1

	for _, rule := range cfg.DirectoryRules {
		pattern := rule.Pattern
		if strings.HasPrefix(pattern, "~/") {
			pattern = filepath.Join(homeDir, pattern[2:])
		} else if pattern == "~" {
			pattern = homeDir
		}

		// Normalize: ensure trailing separator for prefix matching.
		if !strings.HasSuffix(pattern, string(filepath.Separator)) {
			pattern += string(filepath.Separator)
		}
		checkDir := dir
		if !strings.HasSuffix(checkDir, string(filepath.Separator)) {
			checkDir += string(filepath.Separator)
		}

		if strings.HasPrefix(checkDir, pattern) && len(pattern) > bestLen {
			best = rule.Profile
			bestLen = len(pattern)
		}
	}

	if bestLen >= 0 {
		return best, true
	}
	return "", false
}

// defaultAppConfig returns an AppConfig populated with sensible defaults.
func defaultAppConfig(cfgPath string) AppConfig {
	homeDir, _ := os.UserHomeDir()
	return AppConfig{
		ProfilesPath: filepath.Join(homeDir, ".git-ctx-profiles.json"),
		Worktree: AppWorktreeConfig{
			DefaultMode: "symlink",
		},
		path: cfgPath,
	}
}

// loadAppConfig reads the YAML config file at cfgPath.
// If the file does not exist, defaults are returned without error.
func loadAppConfig(cfgPath string) (AppConfig, error) {
	cfg := defaultAppConfig(cfgPath)

	data, err := os.ReadFile(cfgPath)
	if os.IsNotExist(err) {
		return cfg, nil
	}
	if err != nil {
		return cfg, err
	}

	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return cfg, fmt.Errorf("parsing %s: %w", cfgPath, err)
	}
	cfg.path = cfgPath

	// Fill in defaults for fields that were omitted.
	if cfg.Worktree.DefaultMode == "" {
		cfg.Worktree.DefaultMode = "symlink"
	}
	if cfg.ProfilesPath == "" {
		homeDir, _ := os.UserHomeDir()
		cfg.ProfilesPath = filepath.Join(homeDir, ".git-ctx-profiles.json")
	}

	return cfg, nil
}

// initAppConfig writes a scaffolded config file to cfgPath.
// Returns an error if the file already exists and force is false.
func initAppConfig(cfgPath string, force bool) error {
	if _, err := os.Stat(cfgPath); err == nil && !force {
		return fmt.Errorf("%s already exists (use --force to overwrite)", cfgPath)
	}

	homeDir, _ := os.UserHomeDir()
	scaffold := fmt.Sprintf(`# git-ctx configuration
# Generated by: git ctx init
# Run 'git ctx doctor' to validate your setup.

profiles_path: %s

# Map directory prefixes to profiles.
# Longest matching prefix wins.
# Used by 'git ctx profile auto' when no .gitprofilerc is found.
directory_rules:
  - pattern: "~/work"
    profile: work
  - pattern: "~/personal"
    profile: personal

worktree:
  default_mode: symlink  # symlink | copy
  # Hooks run after worktree creation:
  # hooks:
  #   post_create:
  #     - bun install
  #     - npm run setup
`, filepath.Join(homeDir, ".git-ctx-profiles.json"))

	return os.WriteFile(cfgPath, []byte(scaffold), 0644)
}

// defaultAppConfigPath returns ~/.git-ctx.yaml
func defaultAppConfigPath() string {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return ".git-ctx.yaml"
	}
	return filepath.Join(homeDir, ".git-ctx.yaml")
}
